### ISSUE TITLE
Cannot show image

### ISSUE THREAD

**Issue by mistycheney** [unwitting/imageme#4]
Hi,
 
First I would like to thank you for writing this great tool.

I was trying to use this to display about 20 tif images each at about 50 MB. On the webpage, I saw space holders, but not the real image. Is there limitations on the size or format of images that are supported?

Thank you,
Charlie

**Comment by unwitting** [comment]
Hi @mistycheney - thanks for getting in touch. That's interesting, since `tif` is already in the list of supported image formats in that it's involved in `IMAGE_FILE_REGEX` in [imageme.py](/unwitting/imageme/blob/master/imageme.py#L34). Is there any chance you could provide a demonstration image that doesn't display?

**Comment by mistycheney** [comment]
Hi, @unwitting I found this issue has nothing to do with file size, but with the format itself. An example is  https://www.dropbox.com/s/8eix6342bkcthz4/CC35_x5_0005.tif?dl=0

Thanks,

**Comment by unwitting** [comment]
Thanks, reproduced it with that. I'm looking into it.

**Comment by unwitting** [comment]
Ah OK - I had thought that this was something to do with PIL failing on a TIF image, but actually it's simply that browsers don't natively tend to be able to display TIF images. You'll notice if you look at the network tab in this screenshot from your Dropbox link:

![tif_jpeg](https://cloud.githubusercontent.com/assets/1509002/5755845/029a4770-9ca1-11e4-9ed3-d41d54cddb53.jpg)

that the image is actually transmitted from the Dropbox server as a jpeg.

With that in mind, there are a few approaches here:

1. Disable TIF as a supported image format.
2. Keep it enabled as long as the user's environment supports some library (potentially PIL, not looked into whether it could do this yet) for transcoding the image to jpeg data.

**Comment by unwitting** [comment]
Hi @mistycheney - I tried a fix which gets us at least some of the way (see the commit comment for 8f32c4f mentioned above but the approach is to convert image data to jpeg format for browser display using PIL) - but I notice that PIL corrupts the image's colours:

![image_pink](https://cloud.githubusercontent.com/assets/1509002/5756847/34ea1d12-9cac-11e4-97e7-1f2b466ac558.jpg)

No idea why this is happening atm, but at least we can now _display_ them...

**Comment by unwitting** [comment]
I had a bit of a look into this, and I'm not certain your image file isn't a little corrupt in some way. The above colour changing when converting image data with PIL only happens with your file. I tried opening your TIF in GIMP and saving it again - still as a TIF and still with jpeg compression, and this new copy doesn't have the same problems with discolouration:

![screenshot from 2015-01-15 14 09 27](https://cloud.githubusercontent.com/assets/1509002/5758794/49ec4848-9cc0-11e4-8989-d6f423fa8bb3.png)

**Comment by unwitting** [comment]
Do you have control over how your images are generated? Unfortunately since it looks like the problem lay either with your images or with PIL's interpretation of them, there's not much more I can do here now that I've enabled the previewing for TIF images. At least with my new file we know that PIL _can_ do TIFs properly, at least sometimes.

**Comment by unwitting** [comment]
In commit ed68e6e I've added an image telling the user that this image is unsupported for TIFs in the case where PIL is not present, since without PIL we cannot get the browser to display anything other than a broken image.

**Comment by mistycheney** [comment]
Thank you for looking into this issue. I think I will convert all such tif images to PNG. With png, the file size is only half the original and the quality seems as good.

**Comment by unwitting** [comment]
No problem! I'm glad you raised it anyway, since we now have much better support for TIFs than we did :) The system works.
